# Setup
title:               From Ina
tagline:             'My very first website : D'
description:         'Hello, world! '
url:                 http://i7t5.github.io
baseurl:             '/me'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ina Tang
  url:               https://github.com/I7T5
  email:             inatang75@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.1
google_analytics_id: #UA-XXXX-Y
