# Setup
title:               Ina Tang
short_title:         IT
tagline:             ''
description:         "Welcome to my very first website : D"
url:                 https://i7t5.github.io
baseurl:             ''
# paginate:          5
permalink:           pretty

# About/contact
author:
  name:              Ina Tang
  url:               https://github.com/I7T5
  email:             inatang75@outlook.com


# Custom vars
collections:
  posts:
    output:          true
    permalink:       /blog/:categories/:year/:month/:day/:title/

excerpt_separator:   <!--more-->
version:             0.1.0


# Includes
include:
 - _pages

# Gems
plugins:
  - jekyll-paginate
  - jekyll-github-metadata

# Misc
google_analytics_id: #UA-XXXX-Y
